// vue/src/views/Configuration.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
import {
  AvatarSDK,
  DrivingServiceMode,
  Environment,
  LogLevel,
} from '@spatialwalk/avatarkit'
import type { AppConfig } from '../App.vue'

const DASH_URL = 'https://dash.spatialreal.ai'
const STORAGE_KEY = 'avatarkit-playground-config'

const props = defineProps<{
  mode: DrivingServiceMode
}>()

const emit = defineEmits<{
  initialized: [config: AppConfig]
  back: []
}>()

function loadCached() {
  try {
    const raw = localStorage.getItem(STORAGE_KEY)
    if (raw) return JSON.parse(raw) as { appId?: string; token?: string; env?: string }
  } catch { /* ignore */ }
  return {}
}

function saveCache(appId: string, token: string, env: string) {
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify({ appId, token, env }))
  } catch { /* ignore */ }
}

const cached = loadCached()
const appId = ref(cached.appId ?? '')
const token = ref(cached.token ?? '')
const env = ref<Environment>((cached.env as Environment) ?? Environment.intl)
const loading = ref(false)
const error = ref<string | null>(null)

const isSDKMode = computed(() => props.mode === DrivingServiceMode.sdk)
const canInit = computed(() => appId.value.trim() && (!isSDKMode.value || token.value.trim()))

async function handleInit() {
  if (!canInit.value) return
  loading.value = true
  error.value = null
  try {
    await AvatarSDK.initialize(appId.value.trim(), {
      environment: env.value,
      drivingServiceMode: props.mode,
      audioFormat: { channelCount: 1, sampleRate: 16000 },
      logLevel: LogLevel.all,
    })
    if (isSDKMode.value && token.value.trim()) {
      AvatarSDK.setSessionToken(token.value.trim())
    }
    saveCache(appId.value.trim(), token.value.trim(), env.value)
    emit('initialized', {
      appId: appId.value.trim(),
      sessionToken: token.value.trim(),
      environment: env.value,
    })
  } catch (e: any) {
    error.value = e.message || 'Initialization failed'
  } finally {
    loading.value = false
  }
}
</script>

<template>
  <div class="config-view">
    <div class="config-layout">
      <div class="config-container">
        <button class="back-btn" @click="emit('back')">← Back</button>
        <h1>Configuration</h1>
        <p class="config-subtitle">
          Mode: <strong>{{ isSDKMode ? 'SDK' : 'Host' }}</strong>
        </p>
        <div class="config-form">
          <div class="field">
            <label>App ID <span class="required">*</span></label>
            <input
              v-model="appId"
              placeholder="app_xxx"
            />
            <span class="field-hint">
              Get your App ID from the
              <a :href="DASH_URL" target="_blank" rel="noreferrer">Developer Platform</a>
            </span>
          </div>

          <div v-if="isSDKMode" class="field">
            <label>Session Token <span class="required">*</span></label>
            <input
              type="password"
              v-model="token"
              placeholder="Your session token"
            />
            <span class="field-hint">
              Required for server communication in SDK mode
            </span>
          </div>

          <div class="field">
            <label>Environment</label>
            <select v-model="env">
              <option :value="Environment.intl">International</option>
              <option :value="Environment.cn">China</option>
            </select>
          </div>

          <div v-if="error" class="config-error">{{ error }}</div>

          <button
            class="primary init-btn"
            :disabled="!canInit || loading"
            @click="handleInit"
          >
            {{ loading ? 'Initializing...' : 'Initialize SDK' }}
          </button>
        </div>
      </div>
      <a class="config-guide" :href="DASH_URL" target="_blank" rel="noreferrer">
        <img src="/api-key-guide.png" alt="Where to find your App ID and Token" />
      </a>
    </div>
  </div>
</template>

// react/src/views/Configuration.tsx
import { useState } from 'react'
import {
  AvatarSDK,
  DrivingServiceMode,
  Environment,
  LogLevel,
} from '@spatialwalk/avatarkit'
import type { AppConfig } from '../App'

const DASH_URL = 'https://dash.spatialreal.ai'

interface Props {
  mode: DrivingServiceMode
  onInitialized: (config: AppConfig) => void
  onBack: () => void
}

const STORAGE_KEY = 'avatarkit-playground-config'

function loadCached() {
  try {
    const raw = localStorage.getItem(STORAGE_KEY)
    if (raw) return JSON.parse(raw) as { appId?: string; token?: string; env?: string }
  } catch { /* ignore */ }
  return {}
}

function saveCache(appId: string, token: string, env: string) {
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify({ appId, token, env }))
  } catch { /* ignore */ }
}

export default function Configuration({ mode, onInitialized, onBack }: Props) {
  const cached = loadCached()
  const [appId, setAppId] = useState(cached.appId ?? '')
  const [token, setToken] = useState(cached.token ?? '')
  const [env, setEnv] = useState<Environment>((cached.env as Environment) ?? Environment.intl)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const isSDKMode = mode === DrivingServiceMode.sdk
  const canInit = appId.trim() && (!isSDKMode || token.trim())

  const handleInit = async () => {
    if (!canInit) return
    setLoading(true)
    setError(null)
    try {
      await AvatarSDK.initialize(appId.trim(), {
        environment: env,
        drivingServiceMode: mode,
        audioFormat: { channelCount: 1, sampleRate: 16000 },
        logLevel: LogLevel.all,
      })
      if (isSDKMode && token.trim()) {
        AvatarSDK.setSessionToken(token.trim())
      }
      saveCache(appId.trim(), token.trim(), env)
      onInitialized({ appId: appId.trim(), sessionToken: token.trim(), environment: env })
    } catch (e: any) {
      setError(e.message || 'Initialization failed')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="config-view">
      <div className="config-layout">
        <div className="config-container">
          <button className="back-btn" onClick={onBack}>← Back</button>
          <h1>Configuration</h1>
          <p className="config-subtitle">
            Mode: <strong>{isSDKMode ? 'SDK' : 'Host'}</strong>
          </p>

          <div className="config-form">
            <div className="field">
              <label>App ID <span className="required">*</span></label>
              <input
                value={appId}
                onChange={e => setAppId(e.target.value)}
                placeholder="app_xxx"
              />
              <span className="field-hint">
                Get your App ID from the{' '}
                <a href={DASH_URL} target="_blank" rel="noreferrer">
                  Developer Platform
                </a>
              </span>
            </div>

            {isSDKMode && (
              <div className="field">
                <label>Session Token <span className="required">*</span></label>
                <input
                  type="password"
                  value={token}
                  onChange={e => setToken(e.target.value)}
                  placeholder="Your session token"
                />
                <span className="field-hint">
                  Required for server communication in SDK mode
                </span>
              </div>
            )}

            <div className="field">
              <label>Environment</label>
              <select value={env} onChange={e => setEnv(e.target.value as Environment)}>
                <option value={Environment.intl}>International</option>
                <option value={Environment.cn}>China</option>
              </select>
            </div>

            {error && <div className="config-error">{error}</div>}

            <button
              className="primary init-btn"
              disabled={!canInit || loading}
              onClick={handleInit}
            >
              {loading ? 'Initializing...' : 'Initialize SDK'}
            </button>
          </div>
        </div>

        <a className="config-guide" href={DASH_URL} target="_blank" rel="noreferrer">
          <img src="/api-key-guide.png" alt="Where to find your App ID and Token" />
        </a>
      </div>
    </div>
  )
}
