// nextjs-direct/app/page.tsx
'use client'

import { useState, useCallback } from 'react'
import { DrivingServiceMode, Environment } from '@spatialwalk/avatarkit'
import ModeSelect from '@/views/ModeSelect'
import Configuration from '@/views/Configuration'
import Playground from '@/views/Playground'

export interface AppConfig {
  appId: string
  sessionToken: string
  environment: Environment
}

export default function Home() {
  const [step, setStep] = useState<1 | 2 | 3>(1)
  const [mode, setMode] = useState<DrivingServiceMode | null>(null)
  const [config, setConfig] = useState<AppConfig | null>(null)

  const handleModeSelect = useCallback((m: DrivingServiceMode) => {
    setMode(m)
    setStep(2)
  }, [])

  const handleInitialized = useCallback((c: AppConfig) => {
    setConfig(c)
    setStep(3)
  }, [])

  const handleBack = useCallback((toStep: 1 | 2) => {
    setStep(toStep)
  }, [])

  return (
    <div className="app">
      <div className={`view ${step === 1 ? 'active' : ''}`}>
        <ModeSelect onSelect={handleModeSelect} />
      </div>
      <div className={`view ${step === 2 ? 'active' : ''}`}>
        {mode && (
          <Configuration
            mode={mode}
            onInitialized={handleInitialized}
            onBack={() => handleBack(1)}
          />
        )}
      </div>
      <div className={`view ${step === 3 ? 'active' : ''}`}>
        {mode && config && step === 3 && (
          <Playground mode={mode} config={config} />
        )}
      </div>
    </div>
  )
}

// vue/src/App.vue
<script setup lang="ts">
import { ref } from 'vue'
import { DrivingServiceMode, Environment } from '@spatialwalk/avatarkit'
import ModeSelect from './views/ModeSelect.vue'
import Configuration from './views/Configuration.vue'
import Playground from './views/Playground.vue'
import './App.css'

export interface AppConfig {
  appId: string
  sessionToken: string
  environment: Environment
}

const step = ref<1 | 2 | 3>(1)
const mode = ref<DrivingServiceMode | null>(null)
const config = ref<AppConfig | null>(null)

function handleModeSelect(m: DrivingServiceMode) {
  mode.value = m
  step.value = 2
}

function handleInitialized(c: AppConfig) {
  config.value = c
  step.value = 3
}

function handleBack(toStep: 1 | 2) {
  step.value = toStep
}
</script>

<template>
  <div class="app">
    <div :class="['view', { active: step === 1 }]">
      <ModeSelect @select="handleModeSelect" />
    </div>
    <div :class="['view', { active: step === 2 }]">
      <Configuration
        v-if="mode"
        :mode="mode"
        @initialized="handleInitialized"
        @back="handleBack(1)"
      />
    </div>
    <div :class="['view', { active: step === 3 }]">
      <Playground
        v-if="mode && config && step === 3"
        :mode="mode"
        :config="config"
      />
    </div>
  </div>
</template>
